### ISSUE TITLE
pyugt maybe doesn't support python3

### ISSUE THREAD

**Issue by AntonioNero** [lrq3000/pyugt#3] opened 2022-11-23 14:19 UTC
On Linux, when I'm trying to run pyugt as a root (the only way to run it, seems to be) I receive this message "ImportError: No module named configparser".

On some blogs I've read this problem is created because ConfigParser is changed in configparser or config-parser on python3.

Right now I cannot get rid of this problem but I'm trying to solve it.

**Comment by lrq3000** [comment] 2023-01-27 19:14
Sorry I missed your issue before, I only saw it now.

It seems on the contrary that your issue is because in your PATH it's [pointing to a python2 install, not a python3](https://stackoverflow.com/questions/53212248/python-3-x-importerror-no-module-named-configparser-but-module-is-installed). So I would suggest to try to point to the fullpath to your python binary, eg, `/etc/lib/python3/python3 pyugt` to ensure that you are using a Python 3 install, and if it works, you can try to fix your PATH manually.

**Comment by lrq3000** [comment] 2023-03-03 16:57
I could just test again and I can confirm pyugt runs very well on Python 3.10 and 3.11. Closing this issue, please let me know if the issue persists on your side.

**Closed by lrq3000** 2023-03-03 16:57 UTC
